### ISSUE TITLE
BodyPublishers.fromPublisher fails with Content-Length: 0

### ISSUE THREAD

**Issue by hamnis** [http4s/http4s-jdk-http-client#395]
java.lang.IllegalArgumentException: non-positive contentLength: 0
    at java.net.http.HttpRequest$BodyPublishers.fromPublisher(HttpRequest.java:539)
    at org.http4s.client.jdkhttpclient.JdkHttpClient$.$anonfun$apply$4(JdkHttpClient.scala:67)
    at org.http4s.client.jdkhttpclient.JdkHttpClient$.$anonfun$apply$4$adapted(JdkHttpClient.scala:67)
    at scala.Option.fold(Option.scala:263)
    at org.http4s.client.jdkhttpclient.JdkHttpClient$.$anonfun$apply$1(JdkHttpClient.scala:67)

**Comment by amesgen** [comment]
Closed in #396

I will publish point releases later today. If it is urgent you can manually remove the `content-length: 0` headers (see [here](https://github.com/http4s/http4s-jdk-http-client/pull/396#pullrequestreview-617550519)), or use these snapshot builds:

 - `"org.http4s" %% "http4s-jdk-http-client" % "0.3-13-b9b9c44-SNAPSHOT"`
 - `"org.http4s" %% "http4s-jdk-http-client" % "0.4-1-2fd1171-SNAPSHOT"`
 - `"org.http4s" %% "http4s-jdk-http-client" % "0.5-6-1c1dfea-SNAPSHOT"`

**Comment by amesgen** [comment]
JFYI: 0.3.6, 0.4.0-M2 and 0.5.0-M3 have been release with the fix.

**Comment by hamnis** [comment]
Great. thanks!
